-- MySQL Script generated by MySQL Workbench
-- Thu Aug 17 15:25:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_clientes` (
  `cod_cli` INT NOT NULL,
  `nome_cli` VARCHAR(45) NOT NULL,
  `cpf_cli` BIGINT(11) ZEROFILL NOT NULL,
  `telefone_cli` BIGINT(11) ZEROFILL NOT NULL,
  `email_cli` VARCHAR(45) NOT NULL,
  `datanasc_cli` DATE NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  `ativo` CHAR(1) NOT NULL,
  `senha_cli` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cod_cli`),
  UNIQUE INDEX `cpf_cli_UNIQUE` (`cpf_cli` ASC) VISIBLE,
  UNIQUE INDEX `telefone_cli_UNIQUE` (`telefone_cli` ASC) VISIBLE,
  UNIQUE INDEX `email_cli_UNIQUE` (`email_cli` ASC) VISIBLE,
  UNIQUE INDEX `senha_cli_UNIQUE` (`senha_cli` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_compras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_compras` (
  `cod_compra` INT NOT NULL,
  `valor_entrega` FLOAT(5,2) NOT NULL,
  `status_pedido` VARCHAR(45) NOT NULL,
  `data_compra` DATE NOT NULL,
  `cod_cli` INT NOT NULL,
  `forma_pagamento` FLOAT(5,2) NOT NULL,
  `fkcod_cli` INT NOT NULL,
  PRIMARY KEY (`cod_compra`),
  INDEX `fk_tb_compras_tb_clientes1_idx` (`fkcod_cli` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_cidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_cidades` (
  `cod_cid` INT NOT NULL,
  `nome_cid` VARCHAR(45) NOT NULL,
  `estado_cid` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`cod_cid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_enderecos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_enderecos` (
  `cod_endereco` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(5) NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `fkcod_cli` INT NOT NULL,
  `fkcod_cid` INT NOT NULL,
  PRIMARY KEY (`cod_endereco`),
  INDEX `fk_tb_enderecos_tb_clientes1_idx` (`fkcod_cli` ASC) VISIBLE,
  INDEX `fk_tb_enderecos_tb_cidades1_idx` (`fkcod_cid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_categorias` (
  `cod_cate` INT NOT NULL,
  `nome_cate` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_cate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_produtos` (
  `cod_produtos` INT NOT NULL,
  `nome_prod` VARCHAR(45) NOT NULL,
  `valor_prod` FLOAT(5,2) NOT NULL,
  `descricao_prod` VARCHAR(45) NOT NULL,
  `ativo` CHAR(1) NULL,
  `fkcod_cate` INT NOT NULL,
  PRIMARY KEY (`cod_produtos`, `fkcod_cate`),
  INDEX `fk_tb_produtos_tb_categorias1_idx` (`fkcod_cate` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_fotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_fotos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_fotos` (
  `cod_fotos` INT NOT NULL,
  `imagem_foto` VARCHAR(45) NOT NULL,
  `cod_produto` INT NULL,
  `fkcod_produto` INT NOT NULL,
  PRIMARY KEY (`cod_fotos`, `fkcod_produto`),
  INDEX `fk_tb_fotos_tb_produtos1_idx` (`fkcod_produto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_compras_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_compras_produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_compras_produtos` (
  `cod_compra_prod` INT NOT NULL,
  `valor_produto` FLOAT NULL,
  `qntd_prod` INT NULL,
  `fkcod_produto` INT NOT NULL,
  `fkcod_compra` INT NOT NULL,
  PRIMARY KEY (`cod_compra_prod`),
  INDEX `fk_tb_compras_produtos_tb_produtos1_idx` (`fkcod_produto` ASC) VISIBLE,
  INDEX `fk_tb_compras_produtos_tb_compras1_idx` (`fkcod_compra` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
